Ex 6 inheritance
kinley/mkdev pull request #6
Opened 2017-06-07 00:30 UTC by kinley

2017-06-07 08:50 UTC, zverok requested changes
В общем, главное пока что — стиль спек.
И ещё: учитывая что каждое задание продолжает предыдущее, лучше бы их все в одной папке делать (тогда в PR попадали бы только новые куски кода, а не `class Movie` и проч.)

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/lib/movie.rb
> +    raise GenreNotFoundError unless @collection&.genres.include?(genre)
К слову, раз уж решил использовать `&.`, стоит добавить его и ко второй `.`, иначе смысла нету (если коллекции нету, `genres` вернёт `nil`, и `nil.include?` выкинет ошибку).

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/lib/netflix.rb
> +  def withdraw(amount)
Приватный же, наверное? Чёй-то мы пользователю разрешаем забирать деньги в любой момент?

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/movie_collection_spec.rb
> +  end
Посмотри http://betterspecs.org/ (только английскую версию, обязательно), есть несколько важных принципов современного rspec:
* использовать `let` и `subject`, а не instance variables
* использовать гем `rspec-its` по-возможности 
* один тест на `it` (или несколько, объединённых `and`-ом):
```ruby
describe '#all' do
  subject { movies.all }
  it { is_expected.to be_an(Array).and have_attributes(count: 250) }
end
```
* использовать `context` для тестирования поведения одного метода в разных ситуациях:
```ruby
describe '#filter' do
  subject { movies.filter(args) }
  contex 'with empty filters' do
    let(:args) { {} }
  end

  context 'by period' do
  end

  context 'by several filters' do
  end
end
```

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/movie_spec.rb
> +  end
Это должен быть `subject` + несколько малюсеньких `it`

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/movie_spec.rb
> +  end
Это должно быть 4 `context`, а не 4 `it`

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/movie_spec.rb
> +  end
Опять же, 4 контекста. И в спеках зачастую имеет смысл вывести явно пример строки, без подстановки `#{}` — во-первых, меньше возможность того, что две ошибки замаскируют друг друга (напр., `movie.title` оказался `nil`, но спека использует его же), во-вторых, лучше документирует поведение — читатель спеки сразу видит конкретный пример, что будет выведено.

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/movie_spec.rb
> +  end
`let`. И опять же, хорошо бы не пользоваться сервисами тестируемого класса для подготовки данных теста.
А если в `prepare_data` — баг?

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/netflix_spec.rb
> +    expect(@netflix.pay(10)).to eq(@netflix.money)
Тут хорошо подойдёт матчер `expect { ... }.to change`

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/netflix_spec.rb
> +    expect(@netflix.pay(10)).to eq(@netflix.money)
Тут хорошо подойдёт матчер `expect { ... }.to change`

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/netflix_spec.rb
> +          .to(@amount - price)
Опять же, лучше конкретные значения, не взятые из самого же класса.

2017-06-07 08:50 UTC, zverok commented on 6_inheritance/spec/netflix_spec.rb
> +      expect(@netflix.show(filter)).to eq('Now showing: The Terminator')
По задаче, кстати, не возвращать, а печатать ;)

2017-06-08 11:30 UTC, zverok requested changes
Сильно лучше. Продолжай!

2017-06-08 11:30 UTC, zverok commented on 5_oop/demo.rb
> +load 'lib/movie_collection.rb'
так, а кстати, чёй-то у нас `load`, а не `require`?

2017-06-08 11:30 UTC, zverok commented on Gemfile
> +end
Это что и зачем?

2017-06-08 11:30 UTC, zverok commented on lib/movie.rb
> +    raise GenreNotFoundError unless @collection&.genres&.include?(genre)
А знаешь что самое смешное? Что это всё равно не поможет :) Если коллекцию не передали, то тут будет `nil` справа от `unless` и ошибка будет выброшена всегда. Тогда и непонятно, зачем так возиться. То есть либо можно поубирать `&.` либо `raise if @collection && !@collection.genres.include?...`

2017-06-08 11:30 UTC, zverok commented on lib/netflix.rb
> +    PRICE[filter(title: title).first.period]
а если не найден, что будет?

2017-06-08 11:30 UTC, zverok commented on lib/netflix.rb
> +    raise NoPeriodSelected if facets[:period].nil?
Если `period` — обязательный параметр, то так и пиши: `def show(period:, **facets)`

2017-06-08 11:30 UTC, zverok commented on spec/movie_collection_spec.rb
> +  let(:movies) { MovieCollection.new('movies.txt') }
`described_class.new`

2017-06-08 11:30 UTC, zverok commented on spec/movie_collection_spec.rb
> +    end
я бы ещё проверил что все экземпляры правильного класса. и что год например у всех в рамках соотв. периода.

2017-06-08 11:30 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { is_expected.to have_attributes(count: 6) }
`.and all ....` — а то вдруг это первые 6 случайных фильмов?

2017-06-08 11:30 UTC, zverok commented on spec/movie_spec.rb
> +      subject { movie.to_s }
`subject` вынеси перед всеми контекстами. он вычисляется «лениво» (при первом `it`, так что даже когда `movie` не определён ещё, ничего плохого не случится)

2017-06-08 11:30 UTC, zverok commented on spec/movie_spec.rb
> +  def movie_params
`let` же

2017-06-08 11:32 UTC, kinley commented on Gemfile
> +end
Не знаю, копипастнул :)

2017-06-08 13:02 UTC, zverok requested changes

2017-06-08 13:02 UTC, zverok commented on Gemfile
> +end
:-1: Мачете не копипастит!

2017-06-08 13:02 UTC, zverok commented on lib/movie_collection.rb
> +          [value].flatten.map { |v| field.grep(v).any? }.include?(true)
что-то сильно сложно получилось. Давай проще?

2017-06-08 13:02 UTC, zverok commented on lib/theatre.rb
> +  end
Смотри, у тебя одна и та же информация два раза закодирована (совершенно разным способом) в этом и предыдущем методах. Как бы её свести в одну константу и использовать в обоих?..

2017-06-08 13:02 UTC, zverok commented on spec/theatre_spec.rb
> +                      .or have_attributes(genres: include('Adventure')) }
Ну да, для одного прохода `.or` не идеальный тест, но я бы оставил так.

2017-06-09 06:55 UTC, zverok requested changes

2017-06-09 06:55 UTC, zverok commented on lib/movie_collection.rb
> +  protected
`private`. Рубёвый `protected` очень редко нужен, он не так как в других языках работает. Понадобится — ты об этом узнаешь :) А по умолчанию везде пиши `private`

2017-06-09 06:55 UTC, zverok commented on lib/movie_collection.rb
> +    sort_magic_rand(movies).take(1).first
а зачем `take(1)`?

2017-06-09 06:55 UTC, zverok commented on lib/classic_movie.rb
> +      "#{title} - классический фильм, режиссёр #{producer} (#{another_movie_titles})"
Количество, а не названия. Слишком длинное описание будет со всеми названиями.

2017-06-09 06:55 UTC, zverok commented on lib/theatre.rb
> +    times << :evening if !evening_movies.select { |m| m.title == title }.empty?
Тебе не кажется, что код ужасненько повторяется всё ещё? Что здесь, что в предыдущем методе, для утра, вечера, дня — одно и то же написано, только с заменой пары слов.
По-моему, всё что касается периодов стоит вынести в константы (одну или две, например «период → фильтры» и «период → каким часам дня соответствует») и в этих двух методах уж их использовать, м?

2017-06-09 06:55 UTC, zverok commented on spec/movie_collection_spec.rb
> +      it { expect(subject.map(&:year).to_set).to be_subset (1900...1945).to_set }
Я бы сказал так:
```ruby
it { 
  is_expected
   .to all be_an(AncientMovie)
   .and have_attributes(period: :ancient, year: match(1900...1945))
}
```
По-моему читабельнее, не?..

2017-06-09 07:05 UTC, kinley commented on spec/movie_collection_spec.rb
> +      it { expect(subject.map(&:year).to_set).to be_subset (1900...1945).to_set }
Да, это именно то, что я хотел сказать! :)

2017-06-09 20:11 UTC, zverok requested changes
вообще норм уже, потыкал там в пару мелочей

2017-06-09 20:11 UTC, zverok commented on 5_oop.rb
> +require 'new_movie'
я бы сказал, что require_relative более подходит к случаю

2017-06-09 20:11 UTC, zverok commented on lib/movie.rb
> +  def fit?(facet)
я бы сказал что надо два аргумента принимать (ключ, значение), не нужны будут первые две строки

2017-06-09 20:11 UTC, zverok commented on lib/movie.rb
> +      if value.is_a?(Array)
а это зачем?

2017-06-09 20:11 UTC, zverok commented on lib/movie_collection.rb
> +    initial = by_period(facets.delete(:period))
а разве фильтр по периоду не сработает сам, вместе со всеми остальными?

2017-06-09 20:11 UTC, zverok commented on lib/theatre.rb
> +  end
тебе не кажется, что какому периоду какие фильтры соответствуют, тоже можно в константу положить? меньше методов, меньше метапрограмирования, всем проще

2017-06-09 20:11 UTC, zverok commented on lib/movie.rb
> +      if value.is_a?(Array)
а, понял. ну да, получается сложновато. можго распутать через дополнительный метод, но чорт с ним уже

2017-06-09 20:59 UTC, kinley commented on lib/movie.rb
> +  def fit?(facet)
Изначально так и сделал :)

2017-06-09 21:05 UTC, kinley commented on lib/movie_collection.rb
> +    initial = by_period(facets.delete(:period))
Оказывается сработает!

2017-06-13 19:54 UTC, merged