Ex 7 composition
kinley/mkdev pull request #7
Opened 2017-06-13 22:58 UTC by kinley

2017-06-14 12:06 UTC, zverok requested changes

2017-06-14 12:06 UTC, zverok commented on lib/imdb/cashbox.rb
> +      end
Мы с таким уже сталкивались — когда одна из веток `if` кидает исключение, лучше это дело перевернуть:
```ruby
unless ...
  raise Unauthorized 
end
# а здесь else уже не нужен
puts 'Проведена инкассация'
```

2017-06-14 12:06 UTC, zverok commented on lib/imdb/netflix.rb
> +end
Обрати внимание на два факта:
1. у всех нетфликсов должна быть одна касса на всех
2. «сколько мы заработали» (одна касса на всех) и «сколько денег на счету юзера» (у каждого свои) — это два РАЗНЫХ понятия. Допустим, юзер 1 положил 5 баксов, а юзер 2 — 10 (каждый — в свой экземпляр класса Netflix). юзер 1 теперь может посмотреть фильмов на 5 (и его счёт уменьшится до 0), юзер 2 — на 10 (и его счёт уменьшится до 0) — а общая касса всех нетфликсов теперь имеет 15 долларов (а не 5, 10 или 0)

м?

2017-06-14 12:06 UTC, zverok commented on lib/imdb/movie_collection.rb
> +    include Enumerable
И чо, работает? Проверил? Тесты?

2017-06-14 12:06 UTC, zverok commented on spec/imdb/theatre_spec.rb
> +    describe '#take' do
Хорошо бы все методы `Cashbox`а протестировать изолированно — подключив её в пустой тестовый класс. Это поможет определить, нет ли лишней зависимости между модулем и классами куда ты его подключил.

2017-06-16 09:17 UTC, zverok requested changes

2017-06-16 09:17 UTC, zverok commented on lib/imdb/netflix.rb
> +    extend Cashbox
И include, и extend?.. Почему?

2017-06-16 09:17 UTC, zverok commented on lib/imdb/netflix.rb
> +    reset_cashbox
Вот это — нехорошо. В идеале, модуль должен быть устроен так, чтобы тому кто его включил ничего не надо было знать о внутренностях модуля — то есть о том, например, что если не сделать `reset`, всё вообще сломается.

2017-06-16 09:17 UTC, zverok commented on lib/imdb/theatre.rb
> +      reset_cashbox(money)
То же замечание про необходимость `reset`

2017-06-16 09:17 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +    end
Это ты не свой код тестируешь, а «работает ли в руби `include`». Работает, можешь быть уверен даже без тестов :)

2017-06-16 09:17 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +      let(:amount) { Money.new(0) }
Лишний `let`. А если всё же не полениться подключить `rspec-its`, то весь этот `describe` заменяется примерно на:
```ruby
its(:cash) { is_expected.to eq Money.new(0) }
```

2017-06-16 09:17 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +        let(:become) { Money.from_amount(0) }
Эти два `let` тоже читабельности не повышают, впиши прям в код, будет лучше.

2017-06-16 09:17 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +end
А «положить денег» протестировать?..

2017-06-16 10:02 UTC, kinley commented on spec/imdb/cashbox_spec.rb
> +    end
Я здесь проверял, правильно ли я делаю include в тестах :)

2017-06-16 21:43 UTC, zverok requested changes

2017-06-16 21:43 UTC, zverok commented on lib/imdb.rb
> +  $LOAD_PATH.unshift(libdir) unless $LOAD_PATH.include?(libdir)
я не думаю, что это хорошая идея — когда какая-то библиотека изменяет LOAD_PATH. зачем это понадобилось?..

2017-06-16 21:43 UTC, zverok commented on lib/imdb/cashbox.rb
> +    class Unauthorized < RuntimeError; end
(не обязательно использовать, но надо знать, что для таких случаев _многие_ предпочтиают вот такую конструкцию: `Unauthorized = Class.new(RuntimeError)`. значит то же самое абсолютно, но типа слегка короче)

2017-06-16 21:43 UTC, zverok commented on lib/imdb/cashbox.rb
> +      init_money
Я так мыслю, что если прям в `cash` добавить `||=`, оно будет изолировано и красиво, не?..

2017-06-16 21:43 UTC, zverok commented on lib/imdb/netflix.rb
> +    end
а) оно зачем-то нужно?
б) если нужно, то может `alias` достаточно?
в) вообще-то мне кажется вместо обоих методов выше `attr_reader :account` хватило б

2017-06-16 21:43 UTC, zverok commented on lib/imdb/theatre.rb
> +      reset_cashbox(money)
ииии?...

2017-06-16 21:43 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +    end
ну я так и подумал, но теперь-то прибей уж

2017-06-16 21:43 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +      it { is_expected.to be_a(Money).and eq(0) }
я думаю что `to eq Money.new(0)` выражает абсолютно то же самое и притом выразительнее, м?

2017-06-16 21:43 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +          expect { subject }.to change { test_obj.cash }
`change(test_obj, :cash)`. чтобы понять, чем этот вариант лучше, попробуй `rspec --format doc` — увидишь разницу.

2017-06-16 21:43 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +        it { expect { subject }.to_not change { test_obj.cash } }
Нда?.. Я б ошибку бросил.

2017-06-16 21:43 UTC, zverok commented on spec/imdb/cashbox_spec.rb
> +
?..

2017-06-17 12:25 UTC, zverok approved these changes

2017-06-17 12:33 UTC, merged